name: tygrongroep3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - notebook
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip
  - ipython
  - python-dateutil
  - traitlets
  - platformdirs
  - tornado
  - pywin32 
  - psutil
  - typing_extensions
  - zlib
  - zipp
  - tzdata
  - pytorch
  - torchvision
  - cpuonly  
  - networkx
  - pillow
  - pip:
      - ultralytics
      - ultralytics-thop
      - opencv-python
      - pycocotools
      - onnx
      - protobuf
      - tqdm
      - fsspec
      - filelock
      - fonttools
      - jinja2
      - markupsafe
      - kiwisolver
      - packaging
      - pathlib
      - py-cpuinfo
      - pyparsing
      - pyyaml
      - requests
      - datetime
      - contourpy
      - cycler
      - sympy
      - six
      - utils
      - zope-interface
      - charset-normalizer
      - colorama
      - idna
      - urllib3
      - certifi
